name: fig7.8-update
channels:
  - conda-forge
  - chrisroadmap
dependencies:
  - fair==2.1.1
  - h5py
  - ipywidgets
  - jupyter
  - matplotlib
  - nbstripout
  - netCDF4
  - numpy
  - pandas
  - pooch
  - scipy
  - tqdm
  - xarray
